image: python:3.7

stages:
  - test
  - dev

flake8:
  stage: test
  script:
    - pip install pipenv
    - pipenv sync --dev
    - pipenv run flake8 .

test:
  stage: test
  script:
    - pip install pipenv
    - pipenv sync --dev
    - pipenv run pytest
